default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  host: localhost
  port: 5432

development:
  <<: *default
  database: seasonvar_development

test:
  <<: *default
  database: seasonvar_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: seasonvar
  username: seasonvar
  password: 1234567890
